export class EmployeeModel {
    id?: number;  // Make id optional since it will be generated by the server
    name: string = '';
    city: string = '';
    address: string = '';
    contactNo: string = '';
    emailId: string = '';
    pinCode: string = '';
    state: string = '';

    constructor() {
        this.name = '';
        this.city = '';
        this.address = '';
        this.contactNo = '';
        this.emailId = '';
        this.pinCode = '';
        this.state = '';
    }
}